spring.application.name=sales-service
server.port=8081

# CONEXIÓN A BASE DE DATOS PostgreSQL (AWS)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=springuser
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API DE PRODUCTOS (AWS - Localhost porque están en la misma instancia)
products.api.url=http://localhost:8080

# TRANSBANK (Integración)
transbank.commerce-code=597055555532
transbank.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
transbank.return-url=http://localhost:5173/checkout-success
