spring.application.name=users-service
# IMPORTANTE: Puerto 8082 (Para no chocar con Productos 8080 ni Ventas 8081)
server.port=8082

# --- CONEXIÓN A BASE DE DATOS AWS ---
# Revisa que la IP sea la actual de tu laboratorio
spring.datasource.url=jdbc:postgresql://34.201.115.114:5432/ecommerce_db
spring.datasource.username=springuser
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT CONFIGURACIÓN ---
# Clave secreta larga para firmar los tokens
jwt.secret=EstaEsUnaClaveSecretaMuyLargaParaQueFuncioneElAlgoritmoHS512DeSeguridad
# 24 horas de validez (en milisegundos)
jwt.expiration=86400000