spring.application.name=backend

# Conexión a Base de Datos (PostgreSQL en AWS)
spring.datasource.url=jdbc:postgresql://34.201.115.114:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME:springuser}
spring.datasource.password=${DB_PASSWORD:password123}

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor (8080 es el default, pero lo dejamos explícito)
server.port=8080
