spring.application.name=sales-service
# PUERTO IMPORTANTE: 8081
server.port=8081

# CONEXIÓN A BASE DE DATOS (H2 - Desarrollo Local)
#spring.datasource.url=jdbc:h2:mem:salesdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://34.201.115.114:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME:springuser}
spring.datasource.password=${DB_PASSWORD:password123}

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# spring.sql.init.mode=always (Deshabilitado - usamos API de productos)
# spring.jpa.defer-datasource-initialization=true

# H2 - SOLO DESARROLLO LOCAL (comentado para producción)
# spring.datasource.url=jdbc:h2:mem:salesdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true

# API DE PRODUCTOS (AWS)
products.api.url=http://34.201.115.114:8080

# TRANSBANK (Integración)
transbank.commerce-code=597055555532
transbank.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
transbank.return-url=http://localhost:5173/checkout-success